@startuml
'https://plantuml.com/sequence-diagram

autonumber

box Filtrer krediteringer (UC02)
    participant ":Producer" as producer
    participant ":System" as system
end box

activate producer

producer -> system : search(term, channel, category)
activate system
producer <-- system : Programs
deactivate system

@enduml
