@startuml
'https://plantuml.com/sequence-diagram

autonumber

box "Håndtér kreditering (UC03)"
    participant ":Producer" as producer <<Actor>>
    participant ":CreditController" as creditController <<Control>>
    participant ":Credit" as credit <<Entity>>
    participant ":DB" as db
end box

activate producer

alt Create credit
    producer -> creditController : createCredit(person, creditRole, programme)
    activate creditController

    creditController -> credit : <<create>>
    activate credit
    creditController <-- credit : Credit
    deactivate credit

    creditController -> creditController : save(credit)
    activate creditController

    creditController -> db : save(credit)
    activate db
    creditController <-- db
    deactivate db

    creditController <-- creditController
    deactivate creditController

    producer <-- creditController : Credit
    deactivate creditController
else Edit credit

    producer -> creditController : updateCredit(credit)
    activate creditController
    creditController -> db : updateCredit(credit)
    activate db
    creditController <-- db
    deactivate db
    producer <-- creditController : Credit
    deactivate creditController

else Delete credit
    producer -> creditController : deleteCredit(credit)
    activate creditController

    creditController -> db : deleteCredit(credit)
    activate db
    creditController <-- db
    deactivate db

    producer <-- creditController
    deactivate creditController
end

@enduml
