@startuml
'https://plantuml.com/sequence-diagram

autonumber

box Se kreditering (UC01)
    participant ":Producer" as producer
    participant ":System" as system
end box

producer -> system : signIn(username, password)
producer <-- system : Authentication response

producer -> system : exportData(companies, file)
producer <-- system : Data report

@enduml