@startuml
'https://plantuml.com/sequence-diagram

autonumber

box Godkend kreditering (UC11)
    participant ":SystemAdministrator" as administrator
    participant ":System" as system
end box

administrator -> system : signIn(username, password)
administrator <-- system : Authentication response

administrator -> system : getWaitingCredit()
administrator <-- system : Credits waiting approval

administrator -> system : approve(credit)
administrator <-- system : Success

@enduml