@startuml
'https://plantuml.com/sequence-diagram

autonumber

box "Håndtér brugere (UC04)"
    participant ":SystemAdministrator" as administrator
    participant ":System" as system
end box

administrator -> system : signIn(username, password)
administrator <-- system : Authentication response

administrator -> system : updateProgram(program)
system -> system : checkPermission(program)
system -> system : updateProgram(program)
administrator <-- system : Program

@enduml