image: gradle:6.8.3-jdk15

variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

build:
    only:
        - 'master'
        - external_pull_requests
    stage: build
    script: gradle --build-cache build
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: push
        paths:
            - build
            - .gradle

test:
    only:
        - 'master'
        - external_pull_requests
    stage: test
    script: gradle check
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: pull
        paths:
            - build
            - .gradle
