image: gradle:6.8.3-jdk15

variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - touch .env
    - echo DATABASE_LOCAL_HOST=containers-us-west-7.railway.app:6382 >> .env
    - echo DATABASE_LOCAL_USER=postgres >> .env
    - echo DATABASE_LOCAL_PASS=${DATABASE_LOCAL_PASS} >> .env
    - echo DATABASE_LOCAL_DB=railway >> .env

build:
    only:
        - 'master'
        - external_pull_requests
    stage: build
    script: gradle --build-cache build
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: push
        paths:
            - build
            - .gradle

test:
    only:
        - 'master'
        - external_pull_requests
    stage: test
    script: gradle check
    cache:
        key: "$CI_COMMIT_REF_NAME"
        policy: pull
        paths:
            - build
            - .gradle
