@startuml
' https://plantuml.com/sequence-diagram

autonumber

box "Authentication"
    participant ":Producer" as producer
    participant ":AuthController" as authController <<control>>
    participant ":User" as user
    participant ":DB" as db
end box

activate producer
producer -> authController : signIn(username, password)
activate authController
authController -> db : getUserByUsername(username)
activate db
db -> user : <<create>>
activate user
db <-- user : user
deactivate user
authController <-- db : user
deactivate db

authController -> authController : Compare password\n against hash
activate authController
authController <-- authController : Comparison result
deactivate authController

opt if equal
authController --> producer : Successful authentication
end
producer <-- authController : Unsucessful authentication
deactivate authController

@enduml
