@startuml
'https://plantuml.com/sequence-diagram

autonumber

box Se kreditering (UC01)
    participant ":Producer" as producer
    participant ":ProgrammeViewController" as programController <<Control>>
    participant ":DB" as db <<Entity>>
    participant ":Program" as program <<Entity>>
    participant ":Credit" as credit <<Entity>>
    participant ":CreditModal" as creditModal <<Entity>>
end box

activate producer
producer -> programController : showPrograms()
activate programController
programController -> db : getPrograms()
activate db
programController <-- db : Programs
deactivate db
producer <-- programController : Programs
deactivate programController

opt Filtrér krediteringer (UC02)
    ref over producer, programController : UC02
end

producer -> programController : showCredits(program)
activate programController
programController -> db : getCredits(program)
activate db

loop for each program credit
db -> credit : <<create(credit data)>>
activate credit
db <-- credit : Insert credit in list
deactivate credit
end

programController <-- db : Program getCredits
deactivate db
producer <-- programController : Program credits
deactivate programController

producer -> programController : showCredit(credit)
activate programController
programController -> creditModal : <<create(credit)>>
activate creditModal
programController <-- creditModal
deactivate creditModal
producer <-- programController : Credit information
deactivate programController

@enduml
