@startuml
'https://plantuml.com/sequence-diagram

autonumber

box Se kreditering (UC01)
    participant ":Producer" as producer <<Actor>>
    participant ":ProgrammeController" as programController <<Control>>
    participant ":Programme" as program <<Entity>>
    participant ":AuthController" as authController <<Control>>
    participant ":CreditController" as creditController <<Control>>
    participant ":DB" as db
    participant ":Credit" as credit <<Entity>>
end box

activate producer
producer -> programController : getAll()
activate programController
programController -> db : getAll()
activate db

loop for each program credit
db -> program : <<create(programme data)>>
activate program
db <-- program : Insert credit in list
deactivate program
end

programController <-- db : Programs
deactivate db

programController -> authController : user = getUser()
activate authController
deactivate authController

programController -> programController : filter programs\nby user company
activate programController
deactivate programController

producer <-- programController : Programs
deactivate programController

opt Filtrér krediteringer (UC02)
    ref over producer, programController : UC02
end

producer -> program: getCredits()
activate program
program -> programController : getCredits(this)
activate programController
programController -> creditController : getCredits(programme)
activate creditController

creditController -> db : getCredits()
activate db

loop for each program credit
db -> credit : <<create(credit data)>>
activate credit
db <-- credit : Insert credit in list
deactivate credit
end

creditController <-- db : Credits
deactivate db

programController <-- creditController : Program credits
deactivate creditController
program <-- programController : Program credits
deactivate programController
producer <-- program : Program credits

deactivate program
deactivate programController

ref over producer, programController : UC03

@enduml
