@startuml
'https://plantuml.com/sequence-diagram

autonumber

box Filtrer krediteringer (UC02)
    participant ":Producer" as producer
    participant ":ProgrammeController" as programController <<Control>>
    participant ":Program" as program <<Entity>>
    participant ":DB" as db <<Entity>>
end box

activate producer
producer -> programController : search(searchTerm, channel, category)
activate programController

programController -> db : search(searchTerm, channel, category)
activate db
db -> db : find credits like \n term with channel \n and category
activate db
db <-- db
deactivate db

loop for each query result
    db -> program : <<create(search result)>>
    activate program
    db <-- program : Insert program in list
    deactivate program
end
programController <-- db : Programs
deactivate db
producer <-- programController : Programs
deactivate programController
@enduml
