@startuml
' https://plantuml.com/use-case-diagram
left to right direction

actor "Producer (Bruger)" as producer
actor Systemadministrator as administrator
actor Seer as seer
actor Virksomhedsadministrator as virksomhedsadministrator
rectangle "<<aktør>>\nEPG-system" as epg

rectangle "Credit Management System" {
    usecase "Håndtere producere" as (Håndtere producere)
    usecase "Håndtere programmer" as (Håndtere programmer)
    usecase "Håndtere brugere" as (Håndtere brugere)
    usecase "Håndtere krediteringer" as (Håndtere krediteringer)
    usecase "Se krediteringer" as (Se krediteringer)
    usecase "Filtrere krediteringer" as (Filtrere krediteringer)
    usecase "Godkende krediteringer" as (Godkende krediteringer)
    usecase "Eksportere data" as (Eksportere data)
    (Filtrere krediteringer) .> (Se krediteringer) : <<extend>>
}

producer --> (Håndtere programmer)
producer --> (Håndtere krediteringer)

administrator --> (Håndtere brugere)

virksomhedsadministrator --> (Håndtere producere)

seer --> (Se krediteringer)
seer --> (Filtrere krediteringer)

(Se krediteringer) <-- epg

administrator -l-|> virksomhedsadministrator
virksomhedsadministrator -l-|> producer
producer -l-|> seer
(Håndtere krediteringer) .l-> (Se krediteringer) : "<<include>>"

administrator --> (Eksportere data)
administrator --> (Godkende krediteringer)

@enduml