name: Validate JSON

on:
  pull_request:
    branches:
      - master
    paths:
        - '**.json'
  push:
    branches:
      - master
    paths:
        - '**.json'

jobs:
  json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./schema.default.json
          INPUT_JSONS: ./src/main/resources/dk/sdu/swe/db/users.json,./src/main/resources/dk/sdu/swe/db/credits.json,./src/main/resources/dk/sdu/swe/db/programmes.json